### ISSUE TITLE
Evolutions are not completed when I access the database programmatically.

### ISSUE THREAD

**Issue by nemoo** [playframework/play-slick#504] opened 2019-10-07 13:59 UTC
I upgraded my play 2.7.3 application to     
"com.typesafe.play" %% "play-slick" % "4.0.2",
"com.typesafe.play" %% "play-slick-evolutions" % "4.0.2"

I have an evolution script under conf/evolutions/default/1.sql

Still, when starting the application, I get this error: Table “PROJECT” not found; SQL statement:
select “ID”, “NAME” from “PROJECT” [42102-192].

This is build.sbt: my https://github.com/nemoo/play-slick3-example/blob/scala2.13/build.sbt
This is my application.conf: https://github.com/nemoo/play-slick3-example/blob/scala2.13/conf/application.conf

I believe I have configured evolutions in a way that should result in them being executed. Am I doing something wrong?

### Steps to reproduce: 
* Check out https://github.com/nemoo/play-slick3-example/tree/scala2.13
* Run `sbt ~run`

### Expected result:
* Evolutions are run

### Actual result:
* Evolutions are not run

**Comment by ignasi35** [comment] 2019-10-07 14:51
hi @nemoo, this seems like a request for help which may hit a bigger audience at https://discuss.lightbend.com.

**Comment by nemoo** [comment] 2019-10-09 15:53
Good, I additionally submitted it here now: https://discuss.lightbend.com/t/play-2-7-3-slick-3-3-evolutions-not-executed/5186

**Comment by nemoo** [comment] 2019-10-10 10:28
It is interesting that this error occurs only after changing upgrading versions of some libraries (including slick) and scala as can be seen in this diff: 
https://github.com/nemoo/play-slick3-example/compare/play27...scala2.13

In the play27 branch the error mentioned above does not occur, in the scala2.13 branch the error occors.

**Comment by nemoo** [comment] 2019-10-22 18:52
@ignasi35 I have included the steps to reproduce the issue, so verification should be simple now.

**Comment by ignasi35** [comment] 2019-10-24 15:32
Hi @nemoo, I had a quick peek at your code and reproduced the error you mention. I also had a second look at https://github.com/playframework/play-samples/tree/2.7.x/play-scala-slick-example and everything works as expected on the `play-scala-slick-example` sample app.

I suspect there's something else going on on your application. Is it possible you are too eager to use the database inside the constructor of `controllers.Application`?

I'm not 100% what's the change in `play-slick` that could have caused this issue, but this will need more information to isolate the actual cause and decide if it's a bug in `play-slick` or a miss-use of the library.

thanks,

**Comment by hossameldeen** [comment] 2019-11-21 04:57
I have the same issue. I'm not using the database in the constructor of a Controller, though.

**Comment by renatocaval** [comment] 2019-11-28 15:28
@nemoo / @hossameldeen, would you be able to provide a reproducer?

**Comment by nemoo** [comment] 2019-11-28 16:29
@renatocaval that is what I did. See "Steps to reproduce". I even included a previous version that does NOT have this problem including a diff that shows that nothing changed in the code except the versions. 

- https://github.com/nemoo/play-slick3-example/tree/scala2.13  reproduces the problem 
- https://github.com/nemoo/play-slick3-example/compare/play27...scala2.13  compares the problematic version to a version that does not have the problem.

Or do you want the reproduction in a different form? I thought a git repo would be the most precise way possible.

**Comment by nemoo** [comment] 2019-11-28 21:02
Ok I have new information now. I updated the master branch (which does not use the blocking slick api) of my project to play 2.7 and Slick 4 and that went well. That means that the error is somewhere hidden in:
https://github.com/nemoo/play-slick3-example/tree/scala2.13  
I will try to narrow down the problem by removing code. Any hints on potential reasons for my evolutions not being run would be very much appreciated in the meantime.

**Comment by nemoo** [comment] 2019-11-29 14:06
This seems to be the problem:   https://github.com/nemoo/play-slick3-example/blob/c6b99ae24af4ca6313addd903d98c6666fa49269/app/controllers/Application.scala#L34

I am using the database in my play controller, but evolutions have not completely run at that point. 

Somebody on discuss lightbend has the same problem: 
https://discuss.lightbend.com/t/startup-timing-issues-w-database-initialization-and-evolutions/2458
The workaround mentioned there " injecting “ApplicationEvolutions” into objects requiring the database " does not work for me. I still get the same error:  `table "PROJECT" not found`.

How can I make sure evolutions have completed before I use the database?

**Comment by nemoo** [comment] 2019-11-29 15:02
Currently I try using the applicationEvolutions.upToDate function inside the constructor of my controller ( as mentioned here https://github.com/playframework/playframework/pull/8943 and here https://github.com/playframework/playframework/issues/8935 ): 

    while (!applicationEvolutions.upToDate){
      Thread.sleep(100)
      logger.info("still waiting for evolutions to be ready")
    }
  
    db.withSession { implicit session =>
      if (projectRepo.all.length + taskRepo.all.length == 0 && env.isDev) {
        testData.createTestData
      }
    }

But applicationEvolutions.upToDate always returns false and it loops forever.

**Comment by hossameldeen** [comment] 2019-12-11 01:34
Unfortunately, I'd already been done with the project by the time of your reply and it'll be some work to provide a repro at the moment.

One note in case it'll be helpful: AFAIR, my usage didn't involve using the database in the constructor. But can't be sure as the code is far of reach at the moment.

**Comment by renatocaval** [comment] 2019-12-13 11:16
Have you seen @gmethvin's reaction on [Discuss](https://discuss.lightbend.com/t/startup-timing-issues-w-database-initialization-and-evolutions/2458/4)? 

It gives a good insight into why this is happening.
Basically, there is a series of dependencies now and it will cause evolutions to bootstrap once the app is loaded including the controllers. 

You are getting an infinite loop because at first load, the evolutions won't be applied yet and `applicationEvolutions.upToDate` will always return `false`. The controller constructor will never terminate and the app will never finish loading. And then, evolutions never get applied. 

As @mkurz mentioned [here](https://github.com/playframework/playframework/issues/8935#issuecomment-453555110), once the app is loaded, evolutions will be run and then the app is reloaded. 

So, instead of using a while loop, just use an if/else. 

I will send a PR to your original repo with the code that I wrote to make it work.

**Comment by renatocaval** [comment] 2019-12-13 11:31
@nemoo, I'm closing this issue. I will create another one on Play's repo to improve the documentation on this. 

Feel free to re-open if it still not work for you.

**Closed by renatocaval** 2019-12-13 11:31 UTC

**Comment by nemoo** [comment] 2019-12-13 12:58
@renatocaval thanks a lot the [workaround](https://github.com/nemoo/play-slick3-example/pull/10/commits/24af374f96ae34767c3b6f392ebd282314d7bdcf) you provided! Works perfectly.
Looking forward to the documentation improvements and possible code changes in play that @gmethvin talked about on [Discuss](https://discuss.lightbend.com/t/startup-timing-issues-w-database-initialization-and-evolutions/2458/4).
