### ISSUE TITLE
Compile Time DI + Evolutions + CustomSlickDriver (slick-pg)

### ISSUE THREAD

**Issue by mdedetrich** [playframework/play-slick#299] opened 2015-08-08 05:28 UTC
Using the latest `slick-play` dependencies, i.e.
```scala
  "com.typesafe.play" %% "play-slick" % "1.0.1",
  "com.typesafe.play" %% "play-slick-evolutions" % "1.0.1",
```

This is my relevant `application.conf`
```scala
slick.dbs.default.driver="controllers.datamappers.CustomPostgresDriver$"
slick.dbs.default.db.driver="org.postgresql.Driver"
slick.dbs.default.db.url=${DATABASE_URL}
slick.dbs.default.db.password=${?DATABASE_PASSWORD}
slick.dbs.default.db.user=${?DATABASE_USER}
```

This may be an issue with https://github.com/playframework/playframework rather than https://github.com/playframework/play-slick, but I have had issues in regards to getting compile time DI to work (along with play evolutions, which aren't working at all).

As context, I built my application ontop of play-require-angular-seed, the manual DI in question can be seen here (https://github.com/mariussoutier/play-angular-require-seed/blob/master/app/AppLoader.scala).

I never managed to actually set up a `DatabaseConfig[JdbcProfile]` in the `AppLoader` (which is what I want to do, since I wan't the database to be managed by Play's Application Lifecycle). I kept on getting runtime errors, i.e. using

```scala
  val dbConfig:DatabaseConfig[JdbcProfile] = Database.forConfig("slick.dbs.default.db")
```

I get a ```"Configured Slick driver org.postgresql.Driver is not an instance of requested profile slick.profile.BasicProfile"```

I assume you can't use
```scala
val dbConfig = DatabaseConfigProvider.get[JdbcProfile](Play.current)
```

Since this only works if you are doing runtime DI

 In the end, I ended up having to use the standard slick `Database` type, I now have

```scala
  val db = Database.forConfig("slick.dbs.default.db")
  lazy val applicationController = new controllers.Application(defaultCacheApi,db)
```

Which is how you manually set up a database connection in Slick (regardless of whether its `Play` or some other application framework)

Furthermore, I am unable to get evolutions working, at all. This also may be due to using compile time DI (in which case I am unable to find any documentation on how to get evolutions to work). This may generally just be a documentation issue, in which case it probably needs to be improved since I couldn't find anything that helped

**Comment by dotta** [comment] 2015-08-09 09:43
Hi @mdedetrich, thanks for the feedback. Though, because it's not clear if the issue is due to a bug or an improper usage, would you mind discussing it in the [playframework user mailing list](https://groups.google.com/forum/#!forum/play-framework) first.

I'm closing this ticket for the moment. If an issue is confirmed in play-slick, please feel free to reopen (or create a new one if more appropriate).

**Closed by dotta** 2015-08-09 09:43 UTC
