### ISSUE TITLE
Unique Indexes break referential integrity.

### ISSUE THREAD

**Issue by JethroMV** [playframework/play-slick#495] opened 2019-08-19 14:59 UTC
Hi All,
  I have a working slick project, which includes foreign keys.  However, if we add a unique index the referential integrity of the foreign keys is ignored.

I have [adapted](https://github.com/JethroMV/play-slick/tree/master/samples/basic) the basic sample to demonstrate the issue.  Run the tests and they will fail. But comment out the two
`    def uniqueIndex = index("uniqueIndex", (name), unique = true)`
lines and the tests pass.

The Foreign key is defined as:
`    def dog = foreignKey("DOGFK", dogName, Dogs)(_.name, onUpdate = ForeignKeyAction.Restrict, onDelete = ForeignKeyAction.Restrict)`

Thanks for any assistance.

Jethro

**Comment by renatocaval** [comment] 2019-08-27 09:38
Hi @JethroMV, I don't think this is related to play-slick, but with Slick itself. It's better to request help on their Gitter channel and look for open issues there as well. https://github.com/slick/slick/

I agree that this is unexpected behaviour, but on the other hand, I don't think it's needed to create an index PK columns. They are usually already indexed. That unnecessary combination may be the cause of the bug in Slick.

I'm closing it as it's not related to the play-slick plugin.

**Closed by renatocaval** 2019-08-27 09:38 UTC
Labels: triage

**Comment by JethroMV** [comment] 2019-08-27 09:42
Aah thanks, will take it up over there.
The problem also occurs if the unique index is applied to a non-primary key.  That was just for the example.
Cheers
